services:
  bot:
    image: gunsh1p/cu-daily-task
    restart: always
    env_file: .env
    depends_on:
      - db
  db:
    image: mariadb:11.4.2
    restart: always
    environment:
        MARIADB_ROOT_PASSWORD: qwerty123
        MARIADB_DATABASE: cu-daily-task
        MARIADB_USER: bot
        MARIADB_PASSWORD: qwerty123
    volumes:
        - "./data/db:/var/lib/mysql"